import { z } from "zod";
import { startAttempt } from "@/core/attempts";
import { guardStudent } from "../_lib/student";
import { fail, failValidation, ok } from "../_lib/respond";

export const runtime = "nodejs";

const Body = z.object({
  assignmentId: z.uuid(),
  // Generated by the client BEFORE it has reached the network. This is the
  // idempotency key: tapping Start twice on a flaky connection must not create
  // two sittings.
  clientAttemptId: z.uuid(),
});

export async function POST(request: Request) {
  const check = await guardStudent();
  if (!check.ok) return check.response;

  let raw: unknown;
  try {
    raw = await request.json();
  } catch {
    return fail("VALIDATION_FAILED", "We could not read that request.");
  }

  const parsed = Body.safeParse(raw);
  if (!parsed.success) return failValidation(parsed.error);

  const result = await startAttempt(
    {
      organizationId: check.session.actor.organizationId,
      userId: check.session.actor.userId,
    },
    parsed.data.assignmentId,
    parsed.data.clientAttemptId,
  );

  if (!result.ok) {
    return fail(
      result.code === "NOT_FOUND" ? "NOT_FOUND" : "CONFLICT",
      result.message,
    );
  }

  return ok({ attemptId: result.attemptId, resumed: result.resumed });
}
