import { createHmac, randomBytes, timingSafeEqual } from "node:crypto";

/**
 * Signing a delivery.
 *
 * ---------------------------------------------------------------------------
 * The timestamp is INSIDE the signature, and that is the whole point
 * ---------------------------------------------------------------------------
 * The obvious scheme is `hmac(secret, body)`, sent in one header. It proves the
 * body came from us and it is replayable forever: anybody who ever captures one
 * request — a proxy log, a misconfigured load balancer, a bug that echoed a
 * request into an error tracker — can send that exact request again, tomorrow
 * or next year, and the receiver's check passes, because the check is a
 * property of the body alone and the body has not changed.
 *
 * That matters more here than it looks. `results.released` replayed a month
 * later re-imports superseded marks over corrected ones, and nothing in the
 * receiver can tell the difference between the replay and the original.
 *
 * Putting the timestamp beside the signature does not fix it: an attacker
 * replaying the request also chooses the header. The timestamp has to be part
 * of what is signed, so that changing it invalidates the signature and keeping
 * it puts the request outside the receiver's tolerance window. Hence the signed
 * string is `${timestamp}.${body}` and the timestamp travels in its own header
 * for the receiver to check against its own clock.
 *
 * The dot matters too, and is not decoration. Concatenating the two without a
 * separator makes ("17", "59...") and ("175", "9...") produce the same signed
 * string — a canonicalisation ambiguity. A character that cannot appear in the
 * decimal timestamp removes it.
 *
 * ---------------------------------------------------------------------------
 * `v1=` is a version, not a label
 * ---------------------------------------------------------------------------
 * The scheme will change — a different hash, a different canonical string — and
 * when it does, receivers will not all update on the same day. A prefix is what
 * lets one header carry both for a while, and costs nothing now.
 */

export const SIGNATURE_HEADER = "x-sahayak-signature";
export const TIMESTAMP_HEADER = "x-sahayak-timestamp";
export const EVENT_HEADER = "x-sahayak-event";
export const EVENT_ID_HEADER = "x-sahayak-event-id";
export const DELIVERY_HEADER = "x-sahayak-delivery";
export const SIGNATURE_VERSION = "v1";

/**
 * How far out of date a request may be before a receiver should refuse it.
 *
 * Documented here rather than enforced here — we are the sender. Five minutes
 * is generous enough for a school server with a drifting clock and short enough
 * that a captured request is not a usable weapon for long.
 */
export const RECOMMENDED_TOLERANCE_SECONDS = 300;

/** The exact bytes the HMAC is taken over. Exported so a test can pin it. */
export function signedString(timestampSeconds: number, body: string): string {
  return `${timestampSeconds}.${body}`;
}

export function signBody(input: {
  secret: string;
  timestampSeconds: number;
  body: string;
}): string {
  const mac = createHmac("sha256", input.secret)
    .update(signedString(input.timestampSeconds, input.body), "utf8")
    .digest("hex");
  return `${SIGNATURE_VERSION}=${mac}`;
}

/**
 * What a receiver does. Not used in the delivery path — it is here because a
 * signature scheme nobody has written the verifying half of is a scheme with
 * an untested half, and because this is the code the integration document
 * hands a school's developer.
 */
export function verifySignature(input: {
  secret: string;
  timestampSeconds: number;
  body: string;
  header: string;
  now?: number;
  toleranceSeconds?: number;
}): boolean {
  const tolerance = input.toleranceSeconds ?? RECOMMENDED_TOLERANCE_SECONDS;
  const now = input.now ?? Math.floor(Date.now() / 1000);
  if (Math.abs(now - input.timestampSeconds) > tolerance) return false;

  const expected = signBody({
    secret: input.secret,
    timestampSeconds: input.timestampSeconds,
    body: input.body,
  });

  // Length first, because timingSafeEqual throws on a mismatch — and comparing
  // lengths by exception is itself a signal.
  const a = Buffer.from(expected, "utf8");
  const b = Buffer.from(input.header, "utf8");
  if (a.length !== b.length) return false;
  return timingSafeEqual(a, b);
}

/**
 * A new signing secret.
 *
 * 32 bytes of randomness, prefixed so that a secret pasted into the wrong box
 * is recognisable as one. Generated by us and never chosen by a person: a
 * secret somebody picks is a secret somebody has used somewhere else.
 */
export function newSecret(): string {
  return `whsec_${randomBytes(32).toString("base64url")}`;
}
